export const DATA_SET = 'DATA_SET';
export const SET_OPTION = 'SET_OPTION';
export const SET_COUNTER = 'SET_COUNTER';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
